### ISSUE TITLE
Photo Capture Functionality

### ISSUE THREAD

**Issue by Kittysain** [claravox/CSC307-project#1]
create a functionality that allows user to take photo inside the unity project

dev: @Kittysain 
reviewer: @claravox

**Comment by Kittysain** [comment]
Pushed the commit to the develop branch
Look at the scene 1.1 - Kitty 
Modified the FaceDetector script and added the functionality of saving the frame to the screenshot folder.
The FaceDetector script no longer works with a plane. Must work with a UI image object.
After this is verified, close the issue.

**Comment by Kittysain** [comment]
--path not find problem

**Comment by Kittysain** [comment]
modified so that no error occurs if path not exist

**Comment by claravox** [comment]
I have reviewed the code and the fix in your branch works, merged in #39. Resolved
