### ISSUE TITLE
Ability to select face blur/image style

### ISSUE THREAD

**Issue by Kittysain** [claravox/CSC307-project#10]
dev: @Kittysain 
review: @adamperlin

**Comment by Kittysain** [comment]
BlurWithOption Branch
Flower, Mask, Face image overlay option added.
Use the UI mode dropdown list to change mode.
Use the UI on/off button to turn on/off the blurring mode.
Only 1 face has an image overlay.

**Comment by claravox** [comment]
Implemented with #21, BlurWithOptions, and restored_blur_method branch
